# Generated by Django 4.1.4 on 2022-12-26 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='select_option',
            new_name='selectoption',
        ),
    ]
