# Generated by Django 4.1.4 on 2022-12-27 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_rename_select_option_login_selectoption'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='login1',
        ),
    ]
