# Generated by Django 4.1.4 on 2023-01-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_profilepatient_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepatient',
            name='mobileno',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
