# Generated by Django 4.1.4 on 2023-01-17 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_profilepatient_mobileno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilepatient',
            name='mobileno',
        ),
    ]
