# Generated by Django 4.1.4 on 2023-01-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_doctor_hospital_hospital_profile_shedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor_email', models.CharField(max_length=50)),
                ('p_email', models.CharField(max_length=50)),
                ('Hosp_email', models.CharField(max_length=50)),
                ('timeslot', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('day', models.CharField(max_length=50)),
            ],
        ),
    ]
