# Generated by Django 4.1.4 on 2023-01-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_delete_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor_email', models.CharField(max_length=50)),
                ('p_email', models.CharField(max_length=50)),
                ('Hosp_email', models.CharField(max_length=50)),
                ('timein', models.CharField(max_length=10)),
                ('timeout', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=10)),
                ('p_fname', models.CharField(max_length=50)),
                ('p_lame', models.CharField(max_length=50)),
                ('p_phone', models.CharField(max_length=50)),
                ('p_gender', models.CharField(max_length=10)),
                ('p_date_of_birth', models.CharField(max_length=10)),
                ('p_address', models.CharField(max_length=500)),
                ('p_hospital_name', models.CharField(max_length=500)),
                ('p_doctor', models.CharField(max_length=50)),
                ('reason', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
