# Generated by Django 4.1.4 on 2023-01-27 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_delete_hospital_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='hospital_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_H_name', models.CharField(max_length=50)),
                ('p_H_branch', models.CharField(max_length=10)),
                ('p_H_year', models.CharField(max_length=10)),
                ('p_H_address', models.CharField(max_length=300)),
                ('p_H_pin', models.CharField(max_length=10)),
                ('p_H_email', models.CharField(max_length=50)),
                ('p_H_phone', models.CharField(max_length=20)),
                ('P_H_password', models.CharField(max_length=50)),
                ('p_H_photo', models.ImageField(blank=True, null=True, upload_to='image')),
            ],
        ),
    ]
