# Generated by Django 4.1.4 on 2023-01-28 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_hospital_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital_profile',
            name='p_H_photo',
        ),
    ]
